### ISSUE TITLE
tilda fails to build with glib-2.32.0 above

### ISSUE THREAD

**Issue by adaptee** [tsloughter/tilda#3]
In file included from ./tomboykeybinder.h:5:0,
                 from key_grabber.c:28:
/usr/include/glib-2.0/glib/gtypes.h:28:2: Error：#error "Only <glib.h> can be included directly."
make[2]: **\* [tilda-key_grabber.o] Error 1

Also see https://bugs.gentoo.org/show_bug.cgi?id=415527

**Comment by lanoxx** [comment]
This bug is fixed by: https://github.com/lanoxx/tilda/commit/d8d71f63723965d1fb6063ac02f1c1b7625fa23b

**Comment by lanoxx** [comment]
This has been fixed.
